style: 💄 hints for translators
SAP/cloud-sdk-ios-fioriarkit pull request #62
Opened 2021-12-01 14:21 UTC by MarcoEidinger

Some of the related UIs

![Client_CardsForScene](https://user-images.githubusercontent.com/4176826/144250956-934c2dda-1b38-46bd-b5f2-ca35ad0813bb.png)

![Client_Card_Edit](https://user-images.githubusercontent.com/4176826/144250982-fb932ba7-ab9a-4377-a963-555ac13ce19b.png)

![Client_AnchorImage](https://user-images.githubusercontent.com/4176826/144251005-3edc3d6d-9612-426e-9454-6bd6a94ec693.png)

![Client_AnchorImage_Edit](https://user-images.githubusercontent.com/4176826/144251017-06633bac-e75c-4570-be8c-e4058b01cdd3.png)

2021-12-01 14:23 UTC, MarcoEidinger commented
@pgobriensap before requesting translations I added some hints to give them a better context of the vocabulary and terms as well as the use case. Please review

2021-12-01 14:26 UTC, MarcoEidinger commented
@pgobriensap also were the texts verified by UX KM? Some of the terms used, like `Delete` (I would expect `Remove`) or `Save` (I would expect `Done` as data are not immediately saved and Done is used in another form), seem odd to me

2021-12-01 15:37 UTC, MarcoEidinger commented
> @MarcoEidinger I used what is on the files in the [Final MVP Figma](https://www.figma.com/file/kFQGKYE7hnN8eL4jt1vzAH/AR-Creation?node-id=879%3A22157). I can reach out to recommend Remove and Done as it makes more sense for the context.

If you could double-check with them if those texts were vetted by KM and provide suggestion that would be great. Otherwise we could ask Andy for input on the texts

2021-12-01 19:14 UTC, pgobriensap requested changes
I reached out to Sang and she said these changes are okay. 

Done is already a part of the file for the marker flow. I'm not sure how different hints can apply to both scenarios as the string will only map to one value.

2021-12-01 19:14 UTC, pgobriensap commented on Sources/FioriAR/ARCards/Resources/en.lproj/Localizable.strings
> +/* XBUT: to remove an image anchor   */
Delete can be changed to Remove.

2021-12-01 19:14 UTC, pgobriensap commented on Sources/FioriAR/ARCards/Resources/en.lproj/Localizable.strings
> +/* XBUT: button text used in form in which user creates new card (details) of new AR annotation */
Save can be changed to Done.

2021-12-02 21:40 UTC, MarcoEidinger commented on Sources/FioriAR/ARCards/Resources/en.lproj/Localizable.strings
> +/* XBUT: button text used in form in which user creates new card (details) of new AR annotation */
Done

2021-12-02 21:40 UTC, MarcoEidinger commented on Sources/FioriAR/ARCards/Resources/en.lproj/Localizable.strings
> +/* XBUT: to remove an image anchor   */
Done

2021-12-03 03:03 UTC, pgobriensap approved these changes

2021-12-03 03:04 UTC, merged